fix: Add missing PropTypes import to AbilityCard
Fixed white screen issue caused by:
ReferenceError: Can't find variable: PropTypes

Added 'import PropTypes from "prop-types"' to AbilityCard.jsx